name: "FAST_LIO"
version: "0.1.0"
description: "FAST-LIO (Fast LiDAR-Inertial Odometry) is a computationally efficient and robust LiDAR-inertial odometry package."
maintainers:
  - name: "Ji Zhang"
    email: "zhangji@cmu.edu"
  - name: "fins"
    email: "fins@sjtu.edu.cn"
licenses:
  - "GPL-3.0-only"